### ISSUE TITLE
RIch Presence only showing idle state

### ISSUE THREAD

**Issue by sspac** [nekitdev/gd.rpc#11]
![image](https://user-images.githubusercontent.com/72326743/96327203-38dbbf00-0ffd-11eb-8ec3-0276e98b6ebf.png)
Hello, it seems to me that there is a problem with the rich presence, what happens is that it always shows the status of Idle, it does not change at any time and even if it goes to a level, close and re-enter the game it always stays in Idle. I have seen that someone else has already had this problem but did not give details about this, it makes me think that the error would be my Python version which is 3.8 but I do not think it is the problem, I have not edited any files and for some reason it occurs this. _

_Sorry if there are any writing errors, I am not good at English and do the best I can._
_

**Comment by nekitdev** [comment]
Interesting. It seems as though this RPC does not work on pirated version, as it has different offsets. Same with GDPS clients, as most of them are derived from pirated version. So the only solution currently is to get Steam version, sorry.

**Comment by sspac** [comment]
I guess I'll have to buy it from Steam, thanks for taking the time to reply, I really appreciate it.
