### ISSUE TITLE
Make it automatically open when you start the game

### ISSUE THREAD

**Issue by NicolasPL64** [nekitdev/gd.rpc#12]
Something similar to this: https://github.com/zmxhawrhbg/gdrpc/releases

I really like this version more because it shows the currect percentage on the level. But I'll be using zmx's version because I don't have to start the program everytime I open GD.

**Comment by DenoXen** [comment]
eeeh. To make it, rpc need to be as .dll file, writen on c++ or c#
to make it injecteable to gd.

**Comment by nekitdev** [comment]
I have several ideas which I'll try out later.

**Comment by NicolasPL64** [comment]
That's awesome! Is there any way to enable notifications every time you upload a new version?

**Comment by SpookyBear0** [comment]
For a temporary solution you could use [this](https://github.com/SpookyBear0/gdmodloader/)

**Comment by NicolasPL64** [comment]
> For a temporary solution you could use [this](https://github.com/SpookyBear0/gdmodloader/)

Oh but I have to install Python, don't I?

**Comment by MrMelon54** [comment]
It looks like you would have to
