### ISSUE TITLE
Когда я начинаю собирать проект то выдаёт ошибку.

### ISSUE THREAD

**Issue by MerphiG** [nekitdev/gd.rpc#15]
Я собираю проект через питон, идёт всё более менее нормально, но когда я запускаю билд то буквально на мили секунду выдаёт ошибку и экзешник вырубается. Я хз как это фиксануть, мне очень хочется сделать rpc для своего привата, помоги пж, заранее спасибо за помощь.

![image](https://user-images.githubusercontent.com/68493662/124157417-15e63200-dadc-11eb-8786-45d0e5f6a5b9.png)

**Comment by RenslyTheDragon** [comment]
+

**Comment by Timtaran** [comment]
А тут тип по русски писать можно?
